const purgecss = require('@fullhuman/postcss-purgecss');
const purge = purgecss.default || purgecss;

module.exports = {
  plugins: [
    purge({
      content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}', './public/**/*.html'],
      defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
      safelist: [
        'active',
        'show',
        'collapsed',
        'fade',
        'collapse',
        'collapsing',
        'dropdown-menu',
        'dropdown-toggle',
        'check',
        'form-control',
        'form-control-sm',
        'btn-solid',
        'btn-outline',
        'btn-sm',
        'theme-primary',
        'theme-success',
        'theme-secondary',
        'text-center',
        'fg-3',
        'opacity-75',
        'small',
        'h3',
        'bg-black',
        'bg-20',
        'float-end',
        'nav',
        'nav-pills',
        'container',
        'row',
        'col-12',
        'sm:col-4',
        'mb-5',
        'ms-7',
        'align-top',
        'visually-hidden',
      ],
    }),
  ],
};
